/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TaskList */

#ifndef _Included_TaskList
#define _Included_TaskList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TaskList
 * Method:    nativeGetTasks
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TaskList_nativeGetTasks
  (JNIEnv *, jobject);

/*
 * Class:     TaskList
 * Method:    nativeGetTaskInfos
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TaskList_nativeGetTaskInfos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
